defaultPortal: rafal
portals:
  - name: rafal
    portalId: 144435526
    env: prod
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CN7umsjyMRIRAA0AQAAA4C0DQAJYAgEAAPgYxtLvRCCim6gfKO7pDDIUoZASOfsPmZ7bz9d_YhmLLSIF2gQ6TAAABEEAAAB4AAAAAAAAAAAAgAAAAAAABAAAwAcAjvAxPGAQBgBEAGBA_BgGABAgAwAAAAAAPP4DAAAAAAAAAAwEAAAAAAAAAAAAABBCFHTG9-JzpOzdDd_ktnbfV78fsoQPSgNldTFSAFoAYAA
        expiresAt: '2024-04-29T08:44:17.156Z'
    accountType: STANDARD
    personalAccessKey: >-
      CiRldTEtNTZhOS1lMjY5LTQ1OTItOTI3Yi02MTY2MDMzNjQ5Y2UQxtLvRBiim6gfKhkABeaRgplGmCRlTuIOBx8Kxo6naJRhZoiLSgNldTE
